const members = [
  { src: '/Image/About/Member/1920.jpg', name: 'Member 1', role: 'Student' },
  { src: '/Image/About/Member/1921.jpg', name: 'Member 2', role: 'Student' },
  { src: '/Image/About/Member/1922.jpg', name: 'Member 3', role: 'Student' },
  { src: '/Image/About/Member/1923.jpg', name: 'Member 4', role: 'Student' },
  { src: '/Image/About/Member/1924.jpg', name: 'Member 5', role: 'Student' },
  { src: '/Image/About/Member/1925.jpg', name: 'Member 6', role: 'Student' },
  { src: '/Image/About/Member/1926.jpg', name: 'Member 7', role: 'Student' },
  { src: '/Image/About/Member/1927.jpg', name: 'Member 8', role: 'Student' },
  { src: '/Image/About/Member/1928.jpg', name: 'Member 9', role: 'Student' },
  { src: '/Image/About/Member/1929.jpg', name: 'Member 10', role: 'Student' },
  { src: '/Image/About/Member/1930.jpg', name: 'Member 11', role: 'Student' },
  { src: '/Image/About/Member/1931.jpg', name: 'Member 12', role: 'Student' },
  { src: '/Image/About/Member/1932.jpg', name: 'Member 13', role: 'Student' },
  { src: '/Image/About/Member/1933.jpg', name: 'Member 14', role: 'Student' },
  { src: '/Image/About/Member/1934.jpg', name: 'Member 15', role: 'Student' },
  { src: '/Image/About/Member/1935.jpg', name: 'Member 16', role: 'Student' },
  { src: '/Image/About/Member/1936.jpg', name: 'Member 17', role: 'Student' },
  { src: '/Image/About/Member/1937.jpg', name: 'Member 18', role: 'Student' },
  { src: '/Image/About/Member/1939.jpg', name: 'Member 19', role: 'Student' },
  { src: '/Image/About/Member/1940.jpg', name: 'Member 20', role: 'Student' },
  { src: '/Image/About/Member/1941.jpg', name: 'Member 21', role: 'Student' },
  { src: '/Image/About/Member/1942.jpg', name: 'Member 22', role: 'Student' },
  { src: '/Image/About/Member/1943.jpg', name: 'Member 23', role: 'Student' },
  { src: '/Image/About/Member/1944.jpg', name: 'Member 24', role: 'Student' },
  { src: '/Image/About/Member/1945.jpg', name: 'Member 25', role: 'Student' },
  { src: '/Image/About/Member/1946.jpg', name: 'Member 26', role: 'Student' },
  { src: '/Image/About/Member/1947.jpg', name: 'Member 27', role: 'Student' },
  { src: '/Image/About/Member/1948.jpg', name: 'Member 28', role: 'Student' },
  { src: '/Image/About/Member/1949.jpg', name: 'Member 29', role: 'Student' },
  { src: '/Image/About/Member/1950.jpg', name: 'Member 30', role: 'Student' },
  { src: '/Image/About/Member/1951.jpg', name: 'Member 31', role: 'Student' },
  { src: '/Image/About/Member/1952.jpg', name: 'Member 32', role: 'Student' },
  { src: '/Image/About/Member/1953.jpg', name: 'Member 33', role: 'Student' },
  { src: '/Image/About/Member/1954.jpg', name: 'Member 34', role: 'Student' },
];

export default members;
